"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 10:45:51.900548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=40), nullable=False),
    sa.Column('note_id', sa.String(length=40), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scenario_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=False),
    sa.Column('claimed_by', sa.String(length=80), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('forecast', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index('ix_runs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('scenario_edits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=40), nullable=False),
    sa.Column('op', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_edits'))
    )
    with op.batch_alter_table('scenario_edits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_edits_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('issuer', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('issuer', 'subject', name=op.f('uq_users_issuer'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memberships_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id', name=op.f('pk_memberships'))
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('venues',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('open_hour', sa.Integer(), nullable=False),
    sa.Column('close_hour', sa.Integer(), nullable=False),
    sa.Column('service_rate_per_lane', sa.Float(), nullable=False),
    sa.Column('wage_per_staff_hour', sa.Float(), nullable=False),
    sa.Column('history_version', sa.Integer(), nullable=False),
    sa.Column('history_fingerprint', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_venues_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('venue_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('weather', sa.String(length=20), nullable=False),
    sa.Column('show_start', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_events_venue_id_venues')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_events_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('gates',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_gates_venue_id_venues')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_gates')),
    sa.UniqueConstraint('venue_id', 'id', name=op.f('uq_gates_venue_id'))
    )
    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gates_venue_id'), ['venue_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.String(length=40), nullable=False),
    sa.Column('gate_id', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('arrivals', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('weather', sa.String(length=20), nullable=False),
    sa.Column('show_start', sa.Integer(), nullable=True),
    sa.Column('competing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_observations_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_venue_id'), ['venue_id'], unique=False)

    op.create_table('constraints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('scenario_id', sa.String(length=40), nullable=True),
    sa.Column('note_id', sa.String(length=40), nullable=True),
    sa.Column('copied_from', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed_by', sa.String(length=200), nullable=False),
    sa.Column('proposed_via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_via', sa.String(length=20), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_constraints_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constraints'))
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraints_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constraints_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notes_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_event_id'), ['event_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('selected_solution_id', sa.String(length=20), nullable=True),
    sa.Column('selected_by_planner', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_scenarios_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_event_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_event_id'))

    op.drop_table('notes')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraints_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_constraints_event_id'))

    op.drop_table('constraints')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_venue_id'))

    op.drop_table('observations')
    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gates_venue_id'))

    op.drop_table('gates')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_workspace_id'))

    op.drop_table('events')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_workspace_id'))

    op.drop_table('venues')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_workspace_id'))

    op.drop_table('memberships')
    op.drop_table('workspaces')
    op.drop_table('users')
    with op.batch_alter_table('scenario_edits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_edits_scenario_id'))

    op.drop_table('scenario_edits')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_runs_scenario_id'))

    op.drop_table('runs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
